/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    BtnTheme: typeof import('./src/components/BtnTheme.vue')['default']
    Buscar: typeof import('./src/components/Buscar.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Categorias: typeof import('./src/components/Categorias.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    FloatingButtons: typeof import('./src/components/FloatingButtons.vue')['default']
    Galeria: typeof import('./src/components/Galeria.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Mapa: typeof import('./src/components/Mapa.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/Slide.vue')['default']
    Social: typeof import('./src/components/Social.vue')['default']
    Sugerencia: typeof import('./src/components/Sugerencia.vue')['default']
    Sugerencias: typeof import('./src/components/Sugerencias.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    Usuario: typeof import('./src/components/Usuario.vue')['default']
  }
}
