/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Acerca': RouteRecordInfo<'/Acerca', '/Acerca', Record<never, never>, Record<never, never>>,
    '/Admin/Acerca': RouteRecordInfo<'/Admin/Acerca', '/Admin/Acerca', Record<never, never>, Record<never, never>>,
    '/Admin/Administracion': RouteRecordInfo<'/Admin/Administracion', '/Admin/Administracion', Record<never, never>, Record<never, never>>,
    '/Admin/Categoria': RouteRecordInfo<'/Admin/Categoria', '/Admin/Categoria', Record<never, never>, Record<never, never>>,
    '/Admin/Empresa': RouteRecordInfo<'/Admin/Empresa', '/Admin/Empresa', Record<never, never>, Record<never, never>>,
    '/Admin/Favoritos': RouteRecordInfo<'/Admin/Favoritos', '/Admin/Favoritos', Record<never, never>, Record<never, never>>,
    '/Admin/ForgotPass': RouteRecordInfo<'/Admin/ForgotPass', '/Admin/ForgotPass', Record<never, never>, Record<never, never>>,
    '/Admin/GaleriaAbm': RouteRecordInfo<'/Admin/GaleriaAbm', '/Admin/GaleriaAbm', Record<never, never>, Record<never, never>>,
    '/Admin/Item': RouteRecordInfo<'/Admin/Item', '/Admin/Item', Record<never, never>, Record<never, never>>,
    '/Admin/Land': RouteRecordInfo<'/Admin/Land', '/Admin/Land', Record<never, never>, Record<never, never>>,
    '/Admin/Login': RouteRecordInfo<'/Admin/Login', '/Admin/Login', Record<never, never>, Record<never, never>>,
    '/Admin/MenuAbm': RouteRecordInfo<'/Admin/MenuAbm', '/Admin/MenuAbm', Record<never, never>, Record<never, never>>,
    '/Admin/MenuDetalle': RouteRecordInfo<'/Admin/MenuDetalle', '/Admin/MenuDetalle', Record<never, never>, Record<never, never>>,
    '/Admin/NewPass': RouteRecordInfo<'/Admin/NewPass', '/Admin/NewPass', Record<never, never>, Record<never, never>>,
    '/Admin/PageNotFound': RouteRecordInfo<'/Admin/PageNotFound', '/Admin/PageNotFound', Record<never, never>, Record<never, never>>,
    '/Admin/SignUp': RouteRecordInfo<'/Admin/SignUp', '/Admin/SignUp', Record<never, never>, Record<never, never>>,
    '/Admin/SugerenciaAbm': RouteRecordInfo<'/Admin/SugerenciaAbm', '/Admin/SugerenciaAbm', Record<never, never>, Record<never, never>>,
    '/App/Acerca': RouteRecordInfo<'/App/Acerca', '/App/Acerca', Record<never, never>, Record<never, never>>,
    '/App/Ajustes': RouteRecordInfo<'/App/Ajustes', '/App/Ajustes', Record<never, never>, Record<never, never>>,
    '/App/Contacto': RouteRecordInfo<'/App/Contacto', '/App/Contacto', Record<never, never>, Record<never, never>>,
    '/App/Galeria': RouteRecordInfo<'/App/Galeria', '/App/Galeria', Record<never, never>, Record<never, never>>,
    '/App/Home': RouteRecordInfo<'/App/Home', '/App/Home', Record<never, never>, Record<never, never>>,
    '/App/Inicio': RouteRecordInfo<'/App/Inicio', '/App/Inicio', Record<never, never>, Record<never, never>>,
    '/App/LeerQR': RouteRecordInfo<'/App/LeerQR', '/App/LeerQR', Record<never, never>, Record<never, never>>,
    '/App/Menu': RouteRecordInfo<'/App/Menu', '/App/Menu', Record<never, never>, Record<never, never>>,
    '/App/Pedido': RouteRecordInfo<'/App/Pedido', '/App/Pedido', Record<never, never>, Record<never, never>>,
    '/App/Principal': RouteRecordInfo<'/App/Principal', '/App/Principal', Record<never, never>, Record<never, never>>,
    '/App/Reserva': RouteRecordInfo<'/App/Reserva', '/App/Reserva', Record<never, never>, Record<never, never>>,
    '/App/WiFi': RouteRecordInfo<'/App/WiFi', '/App/WiFi', Record<never, never>, Record<never, never>>,
  }
}
